"""Dump a JSON file of deterministic test vectors for the C ambiguous-
ciphertext builder to validate against. The vectors cover:

  - CC=0/1/2/3 AAD layouts (12, 16, 20, 24 bytes after RTP header build)
  - plaintext sizes spanning 1, 2, 5, 13 ciphertext blocks
  - adjustment_offset placed at block index 0, 1, mid, last

Each vector lists the inputs (so the C side recomputes from scratch)
plus the expected outputs (ciphertext bytes + 16-byte tag) so the C
test harness can compare bit-for-bit.

To regenerate: sage attack/hook/dump_ambig_vectors.sage > attack/hook/ambig_vectors.json
"""


# This file was *autogenerated* from the file attack/hook/dump_ambig_vectors.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0xdeadbeef = Integer(0xdeadbeef); _sage_const_0x00000007 = Integer(0x00000007); _sage_const_16 = Integer(16); _sage_const_96 = Integer(96); _sage_const_0x0042 = Integer(0x0042); _sage_const_0 = Integer(0); _sage_const_0x0100 = Integer(0x0100); _sage_const_0xcafebabe = Integer(0xcafebabe); _sage_const_0x10000001 = Integer(0x10000001); _sage_const_1 = Integer(1); _sage_const_0x30 = Integer(0x30); _sage_const_0x35 = Integer(0x35); _sage_const_0x1234 = Integer(0x1234); _sage_const_0x12345678 = Integer(0x12345678); _sage_const_0x10000002 = Integer(0x10000002); _sage_const_32 = Integer(32); _sage_const_0x40 = Integer(0x40); _sage_const_0x4d = Integer(0x4d); _sage_const_0xfffe = Integer(0xfffe); _sage_const_0x10000003 = Integer(0x10000003); _sage_const_12 = Integer(12); _sage_const_0x00aa = Integer(0x00aa); _sage_const_0x0007 = Integer(0x0007); _sage_const_2 = Integer(2)
from binascii import hexlify, unhexlify
import json

load('attack/crypto/util.sage')
load('attack/crypto/gcm.sage')
load('attack/crypto/srtp_kdf.sage')
load('attack/crypto/test_packet_ambiguous.sage')
load('attack/crypto/rtp_header.sage')


def make_vec(name, *, master_key_old, master_key_new, master_salt,
             ssrc, roc, seq, aad, plaintext, adjustment_offset):
    """Run build_ambiguous_under_inner_keys and dump everything we need
    to reproduce in C: inputs (hex) + expected outputs (hex)."""
    r = build_ambiguous_under_inner_keys(
        plaintext, master_key_old, master_key_new, master_salt,
        ssrc, roc, seq,
        adjustment_block_offset=adjustment_offset, aad=aad,
    )
    return {
        "name": name,
        "master_key_old":   hexlify(master_key_old).decode(),
        "master_key_new":   hexlify(master_key_new).decode(),
        "master_salt":      hexlify(master_salt).decode(),
        "ssrc":             int(ssrc),
        "roc":              int(roc),
        "seq":              int(seq),
        "aad":              hexlify(aad).decode(),
        "plaintext":        hexlify(plaintext).decode(),
        "adjustment_offset": int(adjustment_offset),
        "expected_ciphertext": hexlify(r["ciphertext"]).decode(),
        "expected_tag":        hexlify(r["tag16"]).decode(),
        # Surface the derived session keys/nonces so the C test can
        # cross-check each intermediate step.
        "K_enc_old":     hexlify(r["K_enc_old"]).decode(),
        "K_enc_new":     hexlify(r["K_enc_new"]).decode(),
        "nonce_old":     hexlify(r["nonce_old"]).decode(),
        "nonce_new":     hexlify(r["nonce_new"]).decode(),
    }


def main():
    # Common inputs.
    K_OLD = unhexlify("000102030405060708090a0b0c0d0e0f"
                      "101112131415161718191a1b1c1d1e1f")
    K_NEW = unhexlify("ffeeddccbbaa99887766554433221100"
                      "fedcba9876543210ffeeddccbbaa9988")
    SALT  = unhexlify("aabbccddeeff001122334455")   # 12 B
    SSRC, ROC = _sage_const_0xdeadbeef , _sage_const_0x00000007 

    vectors = []

    # Vec 1: tiny plaintext (1 block), CC=0 AAD, adj at offset 0.
    pt1 = b"\xab" * _sage_const_16 
    aad0 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_0x0042 , timestamp=_sage_const_0xdeadbeef ,
                            ssrc=SSRC)
    vectors.append(make_vec("v1_1blk_cc0_adj0",
                            master_key_old=K_OLD, master_key_new=K_NEW,
                            master_salt=SALT, ssrc=SSRC, roc=ROC, seq=_sage_const_0x0042 ,
                            aad=aad0, plaintext=pt1, adjustment_offset=_sage_const_0 ))

    # Vec 2: 2 blocks (32 B), CC=1, adj at block 1 (offset 16).
    pt2 = b"\x11"*_sage_const_16  + b"\x22"*_sage_const_16 
    aad1 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_0x0100 , timestamp=_sage_const_0xcafebabe ,
                            ssrc=SSRC, csrcs=[_sage_const_0x10000001 ])
    vectors.append(make_vec("v2_2blk_cc1_adj1",
                            master_key_old=K_OLD, master_key_new=K_NEW,
                            master_salt=SALT, ssrc=SSRC, roc=ROC, seq=_sage_const_0x0100 ,
                            aad=aad1, plaintext=pt2, adjustment_offset=_sage_const_16 ))

    # Vec 3: 5 blocks (80 B), CC=2, adj at block 2 (mid).
    pt3 = b"".join((i.to_bytes(_sage_const_1 , 'big') * _sage_const_16 ) for i in range(_sage_const_0x30 , _sage_const_0x35 ))
    aad2 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_0x1234 , timestamp=_sage_const_0x12345678 ,
                            ssrc=SSRC, csrcs=[_sage_const_0x10000001 , _sage_const_0x10000002 ])
    vectors.append(make_vec("v3_5blk_cc2_adj2",
                            master_key_old=K_OLD, master_key_new=K_NEW,
                            master_salt=SALT, ssrc=SSRC, roc=ROC, seq=_sage_const_0x1234 ,
                            aad=aad2, plaintext=pt3, adjustment_offset=_sage_const_32 ))

    # Vec 4: 13 blocks (208 B), CC=3, adj at last block.
    pt4 = b"".join((i.to_bytes(_sage_const_1 , 'big') * _sage_const_16 ) for i in range(_sage_const_0x40 , _sage_const_0x4d ))
    aad3 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_0xfffe , timestamp=_sage_const_0x12345678 ,
                            ssrc=SSRC, csrcs=[_sage_const_0x10000001 , _sage_const_0x10000002 , _sage_const_0x10000003 ])
    vectors.append(make_vec("v4_13blk_cc3_adj_last",
                            master_key_old=K_OLD, master_key_new=K_NEW,
                            master_salt=SALT, ssrc=SSRC, roc=ROC, seq=_sage_const_0xfffe ,
                            aad=aad3, plaintext=pt4, adjustment_offset=_sage_const_12 *_sage_const_16 ))

    # Vec 5: no AAD (legacy / boundary). 3 blocks (48 B), adj at block 0.
    pt5 = b"\x55"*_sage_const_16  + b"\x66"*_sage_const_16  + b"\x77"*_sage_const_16 
    vectors.append(make_vec("v5_3blk_no_aad_adj0",
                            master_key_old=K_OLD, master_key_new=K_NEW,
                            master_salt=SALT, ssrc=SSRC, roc=ROC, seq=_sage_const_0x00aa ,
                            aad=b"", plaintext=pt5, adjustment_offset=_sage_const_0 ))

    # Vec 6: ROC ≠ 0 in nonce path (sanity).
    pt6 = b"\xCC"*_sage_const_32 
    aad6 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_0x0007 , timestamp=_sage_const_0xdeadbeef ,
                            ssrc=SSRC)
    vectors.append(make_vec("v6_2blk_high_roc",
                            master_key_old=K_OLD, master_key_new=K_NEW,
                            master_salt=SALT, ssrc=SSRC, roc=_sage_const_0x12345678 , seq=_sage_const_0x0007 ,
                            aad=aad6, plaintext=pt6, adjustment_offset=_sage_const_16 ))

    print(json.dumps(vectors, indent=_sage_const_2 ))


if __name__ == "__main__":
    main()

