"""Build a minimal RTP fixed header (12 B) + optional CSRC list to serve
as AAD for Linphone's inner AES-GCM encryption (paper App. C eq. 20-21,
RFC 8723 §2.1 with extension excluded — Linphone's ms_srtp.cpp clears
`extbit` before handing the synthetic packet to libsrtp).

The 12-byte RTP fixed header (RFC 3550 §5.1) is:

   0                   1                   2                   3
   0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |V=2|P|X|  CC   |M|     PT      |       sequence number         |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |                           timestamp                           |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |           synchronization source (SSRC) identifier            |
  +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
  |            contributing source (CSRC) identifiers             |
  |                             ....                              |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

The total length is 12 + 4 * CC bytes, which is exactly the AAD that
Linphone's inner srtp_protect_aead binds (libsrtp's enc_start - hdr =
12 + 4*CC since the synthetic packet has extbit=0).
"""


# This file was *autogenerated* from the file attack/crypto/rtp_header.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_96 = Integer(96); _sage_const_0 = Integer(0); _sage_const_15 = Integer(15); _sage_const_127 = Integer(127); _sage_const_0xFFFF = Integer(0xFFFF); _sage_const_0x3 = Integer(0x3); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_0x0F = Integer(0x0F); _sage_const_7 = Integer(7); _sage_const_0x7F = Integer(0x7F); _sage_const_12 = Integer(12); _sage_const_42 = Integer(42); _sage_const_0xdeadbeef = Integer(0xdeadbeef); _sage_const_0xcafebabe = Integer(0xcafebabe); _sage_const_0x11111111 = Integer(0x11111111); _sage_const_0x22222222 = Integer(0x22222222); _sage_const_8 = Integer(8); _sage_const_20 = Integer(20); _sage_const_0x10000000 = Integer(0x10000000); _sage_const_60 = Integer(60); _sage_const_72 = Integer(72)
def build_rtp_header(*, version: int = _sage_const_2 ,
                     padding: bool = False,
                     extension: bool = False,
                     csrcs: list = None,
                     marker: bool = False,
                     payload_type: int = _sage_const_96 ,
                     seq: int = _sage_const_0 ,
                     timestamp: int = _sage_const_0 ,
                     ssrc: int = _sage_const_0 ) -> bytes:
    """Return the wire-format RTP fixed header (12 B) + CSRC list.

    `csrcs` is a list of up to 15 contributing-source identifiers
    (uint32). If None or empty, CC = 0 and no CSRC bytes are appended.

    `extension` is left as a regular flag in the byte (so the AAD bytes
    match what Linphone's synthetic packet looks like — with extbit
    cleared by ms_srtp.cpp before inner encryption, this should be
    False for inner-encryption AAD computation).
    """
    csrcs = csrcs or []
    if not (_sage_const_0  <= len(csrcs) <= _sage_const_15 ):
        raise ValueError("RTP allows at most 15 CSRC identifiers")
    if not (_sage_const_0  <= payload_type <= _sage_const_127 ):
        raise ValueError("payload_type must fit in 7 bits")
    if not (_sage_const_0  <= seq <= _sage_const_0xFFFF ):
        raise ValueError("seq must fit in 16 bits")

    cc = len(csrcs)
    byte0 = ((version & _sage_const_0x3 ) << _sage_const_6 ) | ((_sage_const_1  if padding else _sage_const_0 ) << _sage_const_5 )             | ((_sage_const_1  if extension else _sage_const_0 ) << _sage_const_4 ) | (cc & _sage_const_0x0F )
    byte1 = ((_sage_const_1  if marker else _sage_const_0 ) << _sage_const_7 ) | (payload_type & _sage_const_0x7F )

    out = bytearray()
    out.append(byte0)
    out.append(byte1)
    out += seq.to_bytes(_sage_const_2 , "big")
    out += timestamp.to_bytes(_sage_const_4 , "big")
    out += ssrc.to_bytes(_sage_const_4 , "big")
    for csrc in csrcs:
        out += int(csrc).to_bytes(_sage_const_4 , "big")
    assert len(out) == _sage_const_12  + _sage_const_4  * cc
    return bytes(out)


def selftest():
    # CC=0 minimal header
    h0 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_42 , timestamp=_sage_const_0xdeadbeef ,
                          ssrc=_sage_const_0xcafebabe )
    assert len(h0) == _sage_const_12 
    # version=2 padding=0 extension=0 cc=0 → byte0 = 0x80
    # marker=0 pt=96 → byte1 = 0x60
    expected_head = b"\x80\x60" + (_sage_const_42 ).to_bytes(_sage_const_2 , "big") +                     (_sage_const_0xdeadbeef ).to_bytes(_sage_const_4 , "big") +                     (_sage_const_0xcafebabe ).to_bytes(_sage_const_4 , "big")
    assert h0 == expected_head
    print(f"[+] CC=0 header: {len(h0)} B = {h0.hex()}")

    # CC=2 header
    h2 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_42 , timestamp=_sage_const_0xdeadbeef ,
                          ssrc=_sage_const_0xcafebabe ,
                          csrcs=[_sage_const_0x11111111 , _sage_const_0x22222222 ])
    assert len(h2) == _sage_const_12  + _sage_const_8  == _sage_const_20 
    print(f"[+] CC=2 header: {len(h2)} B = {h2.hex()}")
    # byte0 cc field = 2
    assert (h2[_sage_const_0 ] & _sage_const_0x0F ) == _sage_const_2 

    # CC=15 (max)
    h15 = build_rtp_header(payload_type=_sage_const_96 , seq=_sage_const_42 , timestamp=_sage_const_0xdeadbeef ,
                           ssrc=_sage_const_0xcafebabe ,
                           csrcs=list(range(_sage_const_0x10000000 , _sage_const_0x10000000  + _sage_const_15 )))
    assert len(h15) == _sage_const_12  + _sage_const_60  == _sage_const_72 
    print(f"[+] CC=15 header: {len(h15)} B = {h15.hex()}")
    print("[*] OK")


if __name__ == "__main__":
    selftest()

